### PR TITLE
Allow skip keys

### PR DESCRIPTION
**Pull request by bivas6**
Hi, Thanks for the great package!

I suggest this PR to allow users to skip specific keys during the comparison process.

### CODE REVIEW

**Comment by bivas6** [comment]
@ltwlf ping? any comments?

**Comment by orgads** [comment]
ping

**Comment by vixalien** [comment]
pingo

**Comment by orgads** [comment]
@ltwlf Why did you close it?

**Comment by orgads** [comment]
Pushed a new rebased version in #111.

**Pull request closed without merging**
